# server related configuration
server:
  port: 8082
# application related configurations
spring:
  application:
    name: CUSTOMER-SERVICE
# datasource related configuration
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
# eureka server related configurations
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

# actuator related configurations
management:
  endpoints:
    web:
      exposure:
        include: health,info
# Keycloak related configurations

keycloak:
  realm: nimi-project
  auth-server-url: http://localhost:8080/auth
  resource: customer-service
  public-client: true
  autodetect-bearer-only: true

